#!/usr/bin/env python3
"""
Universos por indice para o TradeDesk.
US_INDICES: Russell 1000 (top-1000 por market cap) uniao S&P 500.
B3_TODAS: acoes do IBrX 100 (as ~100+ mais liquidas da B3) + mid caps liquidas.
  Lista compilada das componentes conhecidas do IBrX; pode ter leve defasagem
  de rebalanceamento (o indice muda a cada 4 meses). O filtro de liquidez do
  scan descarta qualquer codigo eventualmente desatualizado ou iliquido.
"""

US_INDICES = [
    "A","AA","AAL","AAOI","AAON","AAPL","ABBV","ABCB","ABNB","ABT",
    "ACA","ACGL","ACI","ACM","ACMR","ACN","ACT","ADBE","ADC","ADI",
    "ADM","ADP","ADSK","AEE","AEIS","AEP","AES","AFG","AFL","AFRM",
    "AGCO","AGNC","AGNCL","AGNCM","AGNCN","AGNCO","AGNCP","AGNCZ","AGX","AHR",
    "AIG","AIT","AIZ","AJG","AKAM","ALAB","ALB","ALGM","ALGN","ALIT",
    "ALL","ALLE","ALLY","ALNY","ALSN","AM","AMAT","AMCR","AMD","AME",
    "AMG","AMGN","AMH","AMKR","AMP","AMT","AMZN","ANET","AON","AOS",
    "APA","APD","APG","APGE","APH","APLD","APO","APOS","APP","APTV",
    "AQNB","AR","ARCC","ARE","ARES","ARMK","AROC","ARW","ARWR","ARXS",
    "ASTS","ATI","ATO","ATR","AUR","AVAV","AVB","AVGO","AVT","AVTR",
    "AVY","AWI","AWK","AXON","AXP","AXSM","AXTA","AYI","AZO","BA",
    "BAC","BAH","BALL","BAX","BBIO","BBY","BDX","BE","BEN","BEPC",
    "BF-B","BG","BIIB","BIO","BJ","BKNG","BKR","BLDR","BLK","BMNR",
    "BMRN","BMY","BNY","BOKF","BPOP","BR","BRK-A","BRK-B","BRKR","BRKRP",
    "BRO","BROS","BRX","BSX","BSY","BTSG","BTSGU","BURL","BWA","BWXT",
    "BX","BXP","BYD","C","CACC","CACI","CAG","CAH","CARR","CART",
    "CASY","CAT","CAVA","CB","CBC","CBOE","CBRE","CBRS","CBSH","CCI",
    "CCK","CCL","CCZ","CDE","CDNS","CDW","CEG","CELH","CET","CF",
    "CFG","CFR","CG","CGNX","CGON","CHD","CHDN","CHE","CHRD","CHRW",
    "CHTR","CHWY","CHYM","CI","CIEN","CIFR","CINF","CL","CLH","CLX",
    "CMC","CMCSA","CME","CMG","CMI","CMS","CMSA","CMSC","CMSD","CNA",
    "CNC","CNM","CNP","COF","COGT","COHR","COIN","COKE","COLB","COMP",
    "COO","COP","COR","CORT","CORZ","CORZZ","COST","CPAY","CPB","CPNG",
    "CPRT","CPT","CQP","CR","CRBG","CRCL","CRDO","CRH","CRL","CRM",
    "CRS","CRUS","CRWD","CRWV","CSCO","CSGP","CSL","CSX","CTAS","CTRE",
    "CTSH","CTVA","CUBE","CVNA","CVS","CVX","CW","CYTK","D","DAL",
    "DAR","DASH","DBX","DCI","DD","DDOG","DDS","DE","DECK","DELL",
    "DG","DGX","DHI","DHR","DINO","DIS","DKNG","DKS","DLR","DLTR",
    "DOC","DOCN","DOCU","DOV","DOW","DPZ","DRI","DT","DTE","DTM",
    "DUK","DUKB","DVA","DVN","DXCM","DY","EA","EAI","EAT","EBAY",
    "ECG","ECHO","ECL","ED","EFX","EG","EHC","EIX","EL","ELAN",
    "ELS","ELV","EME","EMN","EMP","EMR","ENJ","ENS","ENSG","ENTG",
    "EOG","EPD","EPRT","EQH","EQIX","EQR","EQT","ERIE","ES","ESE",
    "ESI","ESS","ET","ETN","ETR","ETSY","EVR","EVRG","EW","EWBC",
    "EXC","EXE","EXEL","EXP","EXPD","EXPE","EXR","F","FAF","FANG",
    "FAST","FBIN","FCFS","FCNCA","FCX","FDS","FDX","FDXF","FE","FFIV",
    "FHN","FICO","FIG","FIS","FISV","FITB","FIVE","FIX","FLEX","FLG",
    "FLR","FLS","FNB","FND","FNF","FORM","FOX","FOXA","FR","FROG",
    "FRT","FRVO","FSLR","FSS","FTAI","FTNT","FTS","FTV","FWONA","FWONK",
    "GAP","GBCI","GD","GDDY","GE","GEHC","GEN","GEV","GFS","GGG",
    "GH","GILD","GIS","GJS","GKOS","GL","GLPI","GLW","GLXY","GM",
    "GME","GMED","GNRC","GOLF","GOOG","GOOGL","GOOGM","GOOGN","GPC","GPN",
    "GRMN","GS","GSAT","GTLS","GVA","GWRE","GWW","H","HAL","HALO",
    "HAS","HBAN","HBANL","HBANM","HBANP","HBANZ","HCA","HD","HEI","HIG",
    "HII","HIMS","HL","HLI","HLT","HNGE","HON","HONA","HOOD","HPE",
    "HPQ","HQY","HR","HRL","HSIC","HST","HSY","HUBB","HUBS","HUM",
    "HUT","HWM","HXL","IBKR","IBM","IBRX","ICE","IDA","IDCC","IDXX",
    "IESC","IEX","IFF","ILMN","IMVT","INCY","INGM","INSM","INTC","INTU",
    "INVH","IONQ","IONS","IOT","IP","IQV","IR","IRM","ISRG","IT",
    "ITT","ITW","IVZ","J","JBHT","JBL","JBTM","JCI","JEF","JKHY",
    "JLL","JNJ","JOBY","JPM","JXN","KDP","KEX","KEY","KEYS","KGS",
    "KHC","KIM","KKR","KKRS","KLAC","KMB","KMI","KMX","KNSL","KNTK",
    "KNX","KO","KR","KRMN","KRYS","KTOS","KVUE","KYMR","L","LAD",
    "LAMR","LDOS","LEA","LECO","LEN","LEVI","LFUS","LGN","LGND","LH",
    "LHX","LII","LIN","LINE","LITE","LKQ","LLY","LLYVA","LLYVK","LMT",
    "LNC","LNG","LNT","LNTH","LOAR","LOGI","LOW","LPLA","LQDA","LRCX",
    "LSCC","LSTR","LTH","LULU","LUMN","LUV","LVS","LYB","LYV","MA",
    "MAA","MAC","MANH","MAR","MAS","MCD","MCHP","MCHPP","MCK","MCO",
    "MDB","MDGL","MDLN","MDLZ","MDT","MEDP","MET","META","MGM","MHK",
    "MIDD","MIRM","MKC","MKL","MKSI","MLI","MLM","MMM","MNST","MO",
    "MOD","MOH","MOS","MP","MPC","MPLX","MPWR","MQ","MRCY","MRK",
    "MRNA","MRSH","MRVL","MS","MSA","MSCI","MSFT","MSGS","MSI","MSM",
    "MSTR","MTB","MTCH","MTD","MTSI","MTZ","MU","MUSA","MWH","MXL",
    "MYRG","NBIX","NCLH","NDAQ","NDSN","NEE","NEM","NET","NEU","NFG",
    "NFLX","NI","NIO","NKE","NLY","NNN","NOC","NOV","NOW","NPO",
    "NRG","NSC","NTAP","NTNX","NTRA","NTRS","NUE","NUVL","NVDA","NVR",
    "NWS","NWSA","NXPI","NXT","NYT","O","OC","ODFL","OGE","OHI",
    "OKE","OKLO","OKTA","OMC","OMF","ON","ONB","ONBPO","ONBPP","ONTO",
    "ORA","ORCL","ORI","ORLY","OSCR","OSK","OTIS","OWL","OXY","P",
    "PAA","PACS","PAG","PANW","PAYC","PAYX","PB","PCAR","PCG","PCOR",
    "PCVX","PEG","PEN","PEP","PFE","PFG","PFGC","PG","PGR","PH",
    "PHM","PINS","PJT","PKG","PL","PLD","PLTR","PLXS","PM","PNC",
    "PNFP","PNR","PNW","PODD","POOL","POWL","PPC","PPG","PPL","PPLC",
    "PR","PRAX","PRH","PRI","PRMB","PRS","PRU","PSA","PSKY","PSX",
    "PTC","PTCT","PTGX","PWR","PYPL","Q","QBTS","QCOM","QNT","QRVO",
    "QXO","R","RAL","RBC","RBLX","RBRK","RCL","RDDT","REG","REGN",
    "REXR","RF","RGA","RGEN","RGLD","RHP","RIOT","RIVN","RJF","RKLB",
    "RKT","RL","RMBS","RMD","ROK","ROKU","ROL","ROP","ROST","RPM",
    "RPRX","RRC","RRR","RRX","RS","RSG","RSI","RTO","RTX","RVMD",
    "RVTY","RYAN","RYN","RYTM","SAIA","SAIL","SANM","SARO","SATA","SBAC",
    "SBUX","SCCO","SCHW","SCI","SE","SEIC","SF","SFD","SFM","SGI",
    "SHW","SIRI","SITM","SJM","SLAB","SLB","SLMBP","SMCI","SMCIP","SMMT",
    "SMTC","SN","SNA","SNAP","SNDK","SNDR","SNEX","SNOW","SNPS","SNX",
    "SO","SOFI","SOJC","SOJD","SOJE","SOLS","SOLV","SOMN","SPCX","SPG",
    "SPGI","SPXC","SRE","SREA","SRRK","SSB","SSD","SSNC","STAG","STE",
    "STLD","STRC","STRD","STRF","STRK","STRL","STT","STX","STZ","SUI",
    "SUN","SW","SWK","SWKS","SWX","SYF","SYK","SYM","SYRE","SYY",
    "T","TAP","TBB","TDG","TDY","TECH","TEL","TEM","TER","TEX",
    "TFC","TGT","TGTX","THC","THG","TJX","TKO","TKR","TLN","TME",
    "TMHC","TMO","TMUS","TOL","TOST","TPG","TPGXL","TPL","TPR","TRGP",
    "TRI","TRMB","TRNO","TROW","TRU","TRV","TSCO","TSLA","TSN","TT",
    "TTAN","TTC","TTD","TTEK","TTMI","TTWO","TW","TWLO","TWST","TXN",
    "TXNM","TXRH","TXT","TYL","U","UAL","UBER","UBSI","UDR","UGI",
    "UHS","UI","ULS","ULTA","UMBF","UNH","UNM","UNP","UPS","URI",
    "USB","USFD","UTHR","V","VEEV","VFC","VG","VIAV","VICI","VICR",
    "VIK","VIRT","VLO","VLTO","VLY","VLYPN","VLYPO","VLYPP","VMC","VMI",
    "VNO","VNOM","VOYA","VRSK","VRSN","VRT","VRTX","VSAT","VSEC","VSH",
    "VST","VTR","VTRS","VZ","W","WAB","WAL","WAT","WBD","WBS",
    "WCC","WDAY","WDC","WEC","WELL","WES","WFC","WH","WLK","WM",
    "WMB","WMG","WMS","WMT","WPC","WRB","WSM","WSO","WST","WTFC",
    "WTRG","WTS","WTW","WULF","WWD","WY","WYNN","XE","XEL","XOM",
    "XPO","XYL","XYZ","YOU","YUM","YUMC","Z","ZBH","ZBRA","ZG",
    "ZION","ZM","ZS","ZTS","ZWS",
]

B3_TODAS = [
    "ABCB4.SA","ABEV3.SA","AESB3.SA","AGRO3.SA","ALOS3.SA","ALUP11.SA","ANIM3.SA","ASAI3.SA","AURE3.SA","AZUL4.SA",
    "AZZA3.SA","B3SA3.SA","BBAS3.SA","BBDC3.SA","BBDC4.SA","BBSE3.SA","BEEF3.SA","BMGB4.SA","BPAC11.SA","BPAN4.SA",
    "BRAP3.SA","BRAP4.SA","BRAV3.SA","BRFS3.SA","BRKM5.SA","CAML3.SA","CASH3.SA","CBAV3.SA","CCRO3.SA","CEAB3.SA",
    "CMIG3.SA","CMIG4.SA","CMIN3.SA","COGN3.SA","CPFE3.SA","CPLE3.SA","CPLE6.SA","CRFB3.SA","CSAN3.SA","CSMG3.SA",
    "CSNA3.SA","CVCB3.SA","CXSE3.SA","CYRE3.SA","DASA3.SA","DIRR3.SA","DXCO3.SA","EGIE3.SA","ELET3.SA","ELET6.SA",
    "EMBR3.SA","ENEV3.SA","ENGI11.SA","ENGI3.SA","ENGI4.SA","EQTL3.SA","EZTC3.SA","FLRY3.SA","FRAS3.SA","GGBR3.SA",
    "GGBR4.SA","GMAT3.SA","GOAU4.SA","GOLL4.SA","GUAR3.SA","HAPV3.SA","HYPE3.SA","IGTI11.SA","INTB3.SA","IRBR3.SA",
    "ITSA3.SA","ITSA4.SA","ITUB3.SA","ITUB4.SA","JBSS3.SA","JHSF3.SA","KEPL3.SA","KLBN11.SA","KLBN4.SA","LEVE3.SA",
    "LJQQ3.SA","LREN3.SA","LWSA3.SA","MATD3.SA","MDIA3.SA","MGLU3.SA","MOTV3.SA","MOVI3.SA","MRFG3.SA","MRVE3.SA",
    "MULT3.SA","MYPK3.SA","NEOE3.SA","NTCO3.SA","ODPV3.SA","ONCO3.SA","PCAR3.SA","PETR3.SA","PETR4.SA","PETZ3.SA",
    "POMO4.SA","PORT3.SA","POSI3.SA","PRIO3.SA","PSSA3.SA","QUAL3.SA","RADL3.SA","RAIL3.SA","RAIZ4.SA","RANI3.SA",
    "RAPT4.SA","RDOR3.SA","RECV3.SA","RENT3.SA","SANB11.SA","SAPR11.SA","SBFG3.SA","SBSP3.SA","SEER3.SA","SIMH3.SA",
    "SLCE3.SA","SMTO3.SA","SRNA3.SA","STBP3.SA","SUZB3.SA","TAEE11.SA","TIMS3.SA","TOTS3.SA","TRPL4.SA","TTEN3.SA",
    "TUPY3.SA","UGPA3.SA","UNIP6.SA","USIM3.SA","USIM5.SA","VALE3.SA","VAMO3.SA","VBBR3.SA","VIVA3.SA","VIVT3.SA",
    "VULC3.SA","WEGE3.SA","WIZC3.SA","YDUQ3.SA",
]

def get_us_indices(): return list(US_INDICES)
def get_b3_todas():   return list(B3_TODAS)
def get_us_large():   return list(US_INDICES)
